### ISSUE TITLE
Could this be implemented as through TS' compiler API?

### ISSUE THREAD

**Issue by fullofcaffeine** [ts-delight/if-expr.macro#2]
Great stuff there. I really miss having if/switch expressions in TS. I use babel for my frontend, but not for the backend.

Would it be possible to implement this directly in TS by using the compiler API (as a kind of plugin)? 

Thanks!

**Comment by lorefnon** [comment]
Technically yes, but typescript compiler API is currently [not stable](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API). And there is no simple way to pass plugins that use the compiler API through tsconfig.json unless we use tsc wrappers like [ttypescript](https://github.com/cevek/ttypescript) which requires consumers to change their build step etc.

In contrast babel-macros has a nicer user friendly API, prevents ordering issues among plugins & fails fast with a clean error when the macro is not included by consumer. If we support typescript compiler plugins then all this will have to be taken care of in each macro in this org.

Also we heavily use babel helpers inside to visit and traverse the AST, so implementing something like this using TS compiler API is likely to be a rewrite (TS compiler internally uses different AST format). 

I currently don't have the time to implement this, but if you do implement this using TS compiler API, I'd be happy to link to that implementation from the README here.

**Comment by fullofcaffeine** [comment]
Thanks for the reply.

Is there any way or workaround that would allow me to use this macro with `tsc`? I'd love to use your plugin(s), but for my backend, I chose to use `tsc`.

I actually was compiling my backend with `Webpack` at some point. `Babel` was part of the pipeline and I used the aforementioned plugin with it, but due to some issues I had with `typegraphql` (which doesn't officially support babel, but only `tsc`) I decided to use `tsc` directly. 

To be honest, `tsc` ended up being faster and simpler to setup. But maybe I can have a setup where I use babel directly and ditch `Webpack` for the backend (for the frontend, I still use it + `@babel/plugin-transform-typescript`). 

Do you have any insights on a possible setup that would be potentially even better than using `tsc` alone and would allow me to take advantage of babel plugins?

Thanks!

**Comment by fullofcaffeine** [comment]
Ping :) do you have any insights about my previous question? Thanks!

**Comment by lorefnon** [comment]
Sorry, I lost track of your last update. 

So, I have generally avoided libraries that make heavy use of decorators and reflect-metadata because the decorator API is kind'a murky territory in JS ecosystem (See [this](https://github.com/mobxjs/mobx/issues/2325) MobX issue for more details). 

Also, I don't have much familiarity with typegraphql but looking at comments like [this](https://github.com/MichalLytek/type-graphql/issues/571#issuecomment-597518567) and planned enhancements like [this](https://github.com/MichalLytek/type-graphql/issues/296), it doesn't look like relying on babel-typescript plugin is a great idea when using this library. 

So, the only other solution I can think of is that you use a two step compilation. In first step you use babel cli along with babel syntax plugins (and not transform plugins) (eg. [@babel/plugin-syntax-decorators](https://babeljs.io/docs/en/babel-plugin-syntax-decorators/), [@babel/plugin-syntax-class-properties](https://babeljs.io/docs/en/babel-plugin-syntax-class-properties/) + any others that your projects needs + [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros)) - this enables babel to parse all the syntax you have and process macros but not transform anything other than macros. 

In second step, you run tsc over the files generated by first step. 

To be honest, for something like if-expr.macro I'd consider this to be an overkill.  

---

On a tangentially related note, if you are interested in GraphQL you may want to checkout [GRelDAL](https://github.com/gammaql/greldal).

**Comment by fullofcaffeine** [comment]
Thanks a lot!

 I'm not really worried about the complexity of setting up, I might try that out. If the performance penalty on the build pipeline is not too great, that might be worth it for m (of course, I wish this or something like `do expressions` it was natively supported by TS instead!).

Cheers!
